# GoReleaser configuration for Terraform Provider
builds:
  - id: terraform-provider-peekaping
    binary: terraform-provider-peekaping
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - docs/
      - examples/

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS"
  algorithm: sha256

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--yes"
      - "--detach-sign"
      - "--armor"
      - "--output"
      - "${signature}"
      - "${artifact}"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^build:'
      - '^chore:'

release:
  github:
    owner: tafaust
    name: terraform-provider-peekaping
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"
  footer: |
    ## Installation

    Use this provider in your Terraform configuration:

    ```hcl
    terraform {
      required_providers {
        peekaping = {
          source  = "tafaust/peekaping"
          version = "~> {{ .Version }}"
        }
      }
    }
    ```

    ## Documentation

    Full documentation is available at: https://registry.terraform.io/providers/tafaust/peekaping/latest/docs
