name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.24'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: |
        go mod download
        go mod verify

    - name: Run tests
      run: make test-ci

    - name: Run linting
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.1

    # - name: Run acceptance tests
    #   run: make testacc
    #   env:
    #     TF_ACC: 1
    #     PEEKAPING_ENDPOINT: http://localhost:8034
    #     PEEKAPING_EMAIL: test@example.com
    #     PEEKAPING_PASSWORD: testpassword
    #     PEEKAPING_TOKEN: 123456

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.24'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: |
        go mod download
        go mod verify

    - name: Build
      run: make build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: terraform-provider-peekaping
        path: terraform-provider-peekaping
